Add functions for integrating CITE-seq data
gao-lab/GLUE pull request #114
Opened 2024-02-04 18:18 UTC by HelloWorldLTY

Dear Authors,

Hi all, I have added functions to implement the functions of integrating gene expression information and protein information from CITE-seq data. I have offered two options to model protein data, either using 1. NBmixture or 2. Normal Distirbution after preprocessing with CLR. It seems that the later option works better. I also provide a method to create the gudiance graph between genes and proteins. 

Sincerely,
Tianyu

2024-02-08 08:05 UTC, Jeff1995 requested changes
Hi @HelloWorldLTY, thank you for the contribution!

I have reviewed the changes and understood the new functionalities and approaches. Below are some further changes that need to be addressed before we can merge.

1. The unit tests are failing because of a new argument `init_fea_emb` in `scglue.models.sc.GraphEncoder.__init__()`. It needs a default value of None, otherwise the standard GLUE model would stop working. Meanwhile, I suppose the `forward` function does not need this argument?
2. The `scglue.utils.generate_prot_guidance_graph()` function should be moved to the `scglue.genomics` module, just like other guidance graph functions.
3. The `scglue.utils.clr()` function is a duplicate of `muon.prot.pp.clr`, so I'd suggest removing this and use `muon` directly.
4. The `NBMixtureDataDecoder` returns one of the NB components randomly per Bernoulli sample rather than a genuine NB mixture. While this might also work in practice, a cleaner approach would require defining an NB mixture distribution and implement a mixture `log_prob`. I suppose [`totalVI`](https://github.com/scverse/scvi-tools/blob/71bbc2004822337281fb085339715660e2334def/scvi/distributions/_negative_binomial.py#L114) did implement one, but we may also achieve the same goal using `torch.distributions.MixtureSameFamily` and `NegativeBinomial`.
5. The new functions need type hints and documentations in a style consistent with the current code base.

Please let me know if you'd like me to address any of these problems or if I've misunderstood some of the code. I would be glad to help!

2024-02-23 13:40 UTC, HelloWorldLTY commented
Hi, sorry for my late reply. I have made the modification based on your comments. For NBMixture model, I used categorical and nb distribution from torch to implement. Please let me know if you have other questions.

2025-08-05 19:29 UTC, HelloWorldLTY commented
It seems like a random issue. https://github.com/Schneegans/dynamic-badges-action/issues/36

2025-09-03 03:06 UTC, Jeff1995 commented
Thx! This was an awkward issue due to a custom coverage badge that has since been broken. I've now switched to codecov and it should be working fine.

> It seems like a random issue. [Schneegans/dynamic-badges-action#36](https://github.com/Schneegans/dynamic-badges-action/issues/36)

2025-09-03 03:14 UTC, merged

2025-09-03 21:16 UTC, HelloWorldLTY commented
Thank you Zhijie!